version: '3.4'

services:

  farmsapi:
    build:
      context: .
      dockerfile: FarmsAPI/Dockerfile
    ports:
      - '8080:80'
      - '8090:443'
    depends_on:
      - seq_in_dc

  animalsapi:
    build:
      context: .
      dockerfile: AnimalsAPI/Dockerfile
    ports:
      - '8081:80'
      - '8091:443'
    depends_on:
      - seq_in_dc

  dummyapi:
    build:
      context: .
      dockerfile: DummyAPI/Dockerfile
    ports:
      - '8082:80'
      - '8092:443'
    depends_on:
      - seq_in_dc

  seq_in_dc:
    image: datalust/seq
    ports:
      - '8005:80'
    environment:
      - ACCEPT_EULA=Y
  

